info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-21T10:14:32.233Z"}
info: Connected to the database. {"timestamp":"2022-02-21T10:14:35.622Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-21T10:17:08.245Z"}
info: Connected to the database. {"timestamp":"2022-02-21T10:17:11.877Z"}
error: 
    status - 500 
    message - Error: "fName" is required
    at new exports.ValidationError (/home/smita/RegisterUser/userRegistrationNlogin/node_modules/@hapi/joi/lib/errors.js:246:9)
    at Object.exports.process (/home/smita/RegisterUser/userRegistrationNlogin/node_modules/@hapi/joi/lib/errors.js:189:29)
    at Object.internals.entry (/home/smita/RegisterUser/userRegistrationNlogin/node_modules/@hapi/joi/lib/validator.js:140:26)
    at Object.exports.entry (/home/smita/RegisterUser/userRegistrationNlogin/node_modules/@hapi/joi/lib/validator.js:26:30)
    at internals.Base.validate (/home/smita/RegisterUser/userRegistrationNlogin/node_modules/@hapi/joi/lib/base.js:534:26)
    at newUserValidator (/home/smita/RegisterUser/userRegistrationNlogin/src/validators/user.validator.js:10:35)
    at Layer.handle [as handle_request] (/home/smita/RegisterUser/userRegistrationNlogin/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/smita/RegisterUser/userRegistrationNlogin/node_modules/express/lib/router/route.js:137:13) 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2022-02-21T10:18:10.217Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-21T10:18:37.911Z"}
info: Connected to the database. {"timestamp":"2022-02-21T10:18:41.385Z"}
error: 
    status - 500 
    message - Error: "email" is required
    at new exports.ValidationError (/home/smita/RegisterUser/userRegistrationNlogin/node_modules/@hapi/joi/lib/errors.js:246:9)
    at Object.exports.process (/home/smita/RegisterUser/userRegistrationNlogin/node_modules/@hapi/joi/lib/errors.js:189:29)
    at Object.internals.entry (/home/smita/RegisterUser/userRegistrationNlogin/node_modules/@hapi/joi/lib/validator.js:140:26)
    at Object.exports.entry (/home/smita/RegisterUser/userRegistrationNlogin/node_modules/@hapi/joi/lib/validator.js:26:30)
    at internals.Base.validate (/home/smita/RegisterUser/userRegistrationNlogin/node_modules/@hapi/joi/lib/base.js:534:26)
    at newUserValidator (/home/smita/RegisterUser/userRegistrationNlogin/src/validators/user.validator.js:10:35)
    at Layer.handle [as handle_request] (/home/smita/RegisterUser/userRegistrationNlogin/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/smita/RegisterUser/userRegistrationNlogin/node_modules/express/lib/router/route.js:137:13) 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2022-02-21T10:18:43.104Z"}
error: 
    status - 500 
    message - Error: User validation failed
    at new MongooseError (/home/smita/RegisterUser/userRegistrationNlogin/node_modules/mongoose/lib/error/mongooseError.js:7:1)
    at new ValidationError (/home/smita/RegisterUser/userRegistrationNlogin/node_modules/mongoose/lib/error/validation.js:27:5)
    at model.Document.invalidate (/home/smita/RegisterUser/userRegistrationNlogin/node_modules/mongoose/lib/document.js:2782:32)
    at /home/smita/RegisterUser/userRegistrationNlogin/node_modules/mongoose/lib/document.js:2574:17
    at /home/smita/RegisterUser/userRegistrationNlogin/node_modules/mongoose/lib/schematype.js:1273:9
    at processTicksAndRejections (internal/process/task_queues.js:77:11) 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2022-02-21T10:19:04.212Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-21T10:19:27.766Z"}
info: Connected to the database. {"timestamp":"2022-02-21T10:19:30.949Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-21T10:19:52.862Z"}
info: Connected to the database. {"timestamp":"2022-02-21T10:19:56.004Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-21T10:24:12.419Z"}
info: Connected to the database. {"timestamp":"2022-02-21T10:24:15.826Z"}
error: 
    status - 500 
    message - ReferenceError: bcrypt is not defined
    at _callee2$ (/home/smita/RegisterUser/userRegistrationNlogin/src/services/user.service.js:12:9)
    at tryCatch (/home/smita/RegisterUser/userRegistrationNlogin/node_modules/regenerator-runtime/runtime.js:63:40)
    at Generator.invoke [as _invoke] (/home/smita/RegisterUser/userRegistrationNlogin/node_modules/regenerator-runtime/runtime.js:294:22)
    at Generator.next (/home/smita/RegisterUser/userRegistrationNlogin/node_modules/regenerator-runtime/runtime.js:119:21)
    at asyncGeneratorStep (/home/smita/RegisterUser/userRegistrationNlogin/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _next (/home/smita/RegisterUser/userRegistrationNlogin/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
    at /home/smita/RegisterUser/userRegistrationNlogin/node_modules/@babel/runtime/helpers/asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (/home/smita/RegisterUser/userRegistrationNlogin/node_modules/@babel/runtime/helpers/asyncToGenerator.js:21:12)
    at Object.newUser (/home/smita/RegisterUser/userRegistrationNlogin/src/services/user.service.js:10:21) 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2022-02-21T10:24:31.043Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-21T10:26:22.409Z"}
info: Connected to the database. {"timestamp":"2022-02-21T10:26:25.946Z"}
error: 
    status - 500 
    message - ReferenceError: myPlaintextPassword is not defined
    at _callee2$ (/home/smita/RegisterUser/userRegistrationNlogin/src/services/user.service.js:13:38)
    at tryCatch (/home/smita/RegisterUser/userRegistrationNlogin/node_modules/regenerator-runtime/runtime.js:63:40)
    at Generator.invoke [as _invoke] (/home/smita/RegisterUser/userRegistrationNlogin/node_modules/regenerator-runtime/runtime.js:294:22)
    at Generator.next (/home/smita/RegisterUser/userRegistrationNlogin/node_modules/regenerator-runtime/runtime.js:119:21)
    at asyncGeneratorStep (/home/smita/RegisterUser/userRegistrationNlogin/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _next (/home/smita/RegisterUser/userRegistrationNlogin/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
    at /home/smita/RegisterUser/userRegistrationNlogin/node_modules/@babel/runtime/helpers/asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (/home/smita/RegisterUser/userRegistrationNlogin/node_modules/@babel/runtime/helpers/asyncToGenerator.js:21:12)
    at Object.newUser (/home/smita/RegisterUser/userRegistrationNlogin/src/services/user.service.js:11:21) 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2022-02-21T10:26:30.405Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-21T10:26:55.668Z"}
info: Connected to the database. {"timestamp":"2022-02-21T10:26:59.053Z"}
error: 
    status - 500 
    message - Error: User validation failed
    at new MongooseError (/home/smita/RegisterUser/userRegistrationNlogin/node_modules/mongoose/lib/error/mongooseError.js:7:1)
    at new ValidationError (/home/smita/RegisterUser/userRegistrationNlogin/node_modules/mongoose/lib/error/validation.js:27:5)
    at model.Document.invalidate (/home/smita/RegisterUser/userRegistrationNlogin/node_modules/mongoose/lib/document.js:2782:32)
    at model.$set (/home/smita/RegisterUser/userRegistrationNlogin/node_modules/mongoose/lib/document.js:1349:12)
    at model.$set (/home/smita/RegisterUser/userRegistrationNlogin/node_modules/mongoose/lib/document.js:1058:16)
    at model.Document (/home/smita/RegisterUser/userRegistrationNlogin/node_modules/mongoose/lib/document.js:148:12)
    at model.Model (/home/smita/RegisterUser/userRegistrationNlogin/node_modules/mongoose/lib/model.js:106:12)
    at new model (/home/smita/RegisterUser/userRegistrationNlogin/node_modules/mongoose/lib/model.js:4911:15) 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2022-02-21T10:27:02.241Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-21T10:27:17.461Z"}
info: Connected to the database. {"timestamp":"2022-02-21T10:27:21.137Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-21T11:22:14.271Z"}
info: Connected to the database. {"timestamp":"2022-02-21T11:22:18.218Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-21T11:23:39.570Z"}
info: Connected to the database. {"timestamp":"2022-02-21T11:23:43.410Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-21T11:23:52.879Z"}
info: Connected to the database. {"timestamp":"2022-02-21T11:23:56.520Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-21T11:24:52.275Z"}
info: Connected to the database. {"timestamp":"2022-02-21T11:24:55.664Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-21T11:25:07.190Z"}
info: Connected to the database. {"timestamp":"2022-02-21T11:25:10.662Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-21T11:28:19.776Z"}
info: Connected to the database. {"timestamp":"2022-02-21T11:28:22.976Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-21T11:29:29.333Z"}
info: Connected to the database. {"timestamp":"2022-02-21T11:29:32.588Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-21T11:32:43.280Z"}
info: Connected to the database. {"timestamp":"2022-02-21T11:32:46.417Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-21T11:44:36.762Z"}
info: Connected to the database. {"timestamp":"2022-02-21T11:44:46.030Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-21T11:45:05.391Z"}
info: Connected to the database. {"timestamp":"2022-02-21T11:45:08.444Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-21T11:46:40.227Z"}
info: Connected to the database. {"timestamp":"2022-02-21T11:46:43.216Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-21T11:46:48.744Z"}
info: Connected to the database. {"timestamp":"2022-02-21T11:46:52.104Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-21T11:47:11.732Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-21T11:47:15.022Z"}
info: Connected to the database. {"timestamp":"2022-02-21T11:47:20.037Z"}
error: 
    status - 500 
    message - Error: User validation failed
    at new MongooseError (/home/smita/RegisterUser/userRegistrationNlogin/node_modules/mongoose/lib/error/mongooseError.js:7:1)
    at new ValidationError (/home/smita/RegisterUser/userRegistrationNlogin/node_modules/mongoose/lib/error/validation.js:27:5)
    at model.Document.invalidate (/home/smita/RegisterUser/userRegistrationNlogin/node_modules/mongoose/lib/document.js:2782:32)
    at model.$set (/home/smita/RegisterUser/userRegistrationNlogin/node_modules/mongoose/lib/document.js:1349:12)
    at model.$set (/home/smita/RegisterUser/userRegistrationNlogin/node_modules/mongoose/lib/document.js:1058:16)
    at model.Document (/home/smita/RegisterUser/userRegistrationNlogin/node_modules/mongoose/lib/document.js:148:12)
    at model.Model (/home/smita/RegisterUser/userRegistrationNlogin/node_modules/mongoose/lib/model.js:106:12)
    at new model (/home/smita/RegisterUser/userRegistrationNlogin/node_modules/mongoose/lib/model.js:4911:15) 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2022-02-21T11:47:30.912Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-21T11:48:34.092Z"}
info: Connected to the database. {"timestamp":"2022-02-21T11:48:37.010Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-21T11:48:52.692Z"}
info: Connected to the database. {"timestamp":"2022-02-21T11:48:56.547Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-21T11:50:05.427Z"}
info: Connected to the database. {"timestamp":"2022-02-21T11:50:09.197Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-21T13:07:58.796Z"}
info: Connected to the database. {"timestamp":"2022-02-21T13:08:02.256Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-21T13:08:35.844Z"}
info: Connected to the database. {"timestamp":"2022-02-21T13:08:39.429Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-21T13:11:09.222Z"}
info: Connected to the database. {"timestamp":"2022-02-21T13:11:13.762Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-21T13:12:18.460Z"}
info: Connected to the database. {"timestamp":"2022-02-21T13:12:22.235Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-21T13:12:27.383Z"}
info: Connected to the database. {"timestamp":"2022-02-21T13:12:31.189Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-21T13:15:42.134Z"}
info: Connected to the database. {"timestamp":"2022-02-21T13:15:45.750Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-21T13:16:02.965Z"}
info: Connected to the database. {"timestamp":"2022-02-21T13:16:07.458Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-21T13:16:41.284Z"}
info: Connected to the database. {"timestamp":"2022-02-21T13:16:45.125Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-21T13:17:45.894Z"}
info: Connected to the database. {"timestamp":"2022-02-21T13:17:54.466Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-21T13:18:25.534Z"}
info: Connected to the database. {"timestamp":"2022-02-21T13:18:29.034Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-21T13:21:55.458Z"}
info: Connected to the database. {"timestamp":"2022-02-21T13:21:56.037Z"}
error: 
      status - 11000
      message - E11000 duplicate key error collection: UserDB.users index: email_1 dup key: { email: "smita12@gmail.com" } 
      url - /api/v1/users 
      method - POST 
      IP - ::1
     {"timestamp":"2022-02-21T13:22:26.293Z"}
error: 
    status - 500 
    message - RangeError [ERR_HTTP_INVALID_STATUS_CODE]: Invalid status code: 11000
    at new NodeError (internal/errors.js:322:7)
    at ServerResponse.writeHead (_http_server.js:259:11)
    at ServerResponse.writeHead (/home/smita/RegisterUser/userRegistrationNlogin/node_modules/on-headers/index.js:44:26)
    at ServerResponse._implicitHeader (_http_server.js:250:8)
    at write_ (_http_outgoing.js:711:9)
    at ServerResponse.end (_http_outgoing.js:825:5)
    at ServerResponse.send (/home/smita/RegisterUser/userRegistrationNlogin/node_modules/express/lib/response.js:221:10)
    at ServerResponse.json (/home/smita/RegisterUser/userRegistrationNlogin/node_modules/express/lib/response.js:267:15)
    at appErrorHandler (/home/smita/RegisterUser/userRegistrationNlogin/src/middlewares/error.middleware.js:36:26)
    at Layer.handle_error (/home/smita/RegisterUser/userRegistrationNlogin/node_modules/express/lib/router/layer.js:71:5) 
    url - /api/v1/users 
    method - POST 
    IP - ::1
   {"timestamp":"2022-02-21T13:22:26.364Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-21T13:23:09.203Z"}
info: Connected to the database. {"timestamp":"2022-02-21T13:23:09.227Z"}
error: 
    status - 500 
    message - ReferenceError: jwt is not defined
    at _callee3$ (/home/smita/RegisterUser/userRegistrationNlogin/src/services/user.service.js:27:13)
    at tryCatch (/home/smita/RegisterUser/userRegistrationNlogin/node_modules/regenerator-runtime/runtime.js:63:40)
    at Generator.invoke [as _invoke] (/home/smita/RegisterUser/userRegistrationNlogin/node_modules/regenerator-runtime/runtime.js:294:22)
    at Generator.next (/home/smita/RegisterUser/userRegistrationNlogin/node_modules/regenerator-runtime/runtime.js:119:21)
    at asyncGeneratorStep (/home/smita/RegisterUser/userRegistrationNlogin/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _next (/home/smita/RegisterUser/userRegistrationNlogin/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-02-21T13:23:10.952Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-21T13:23:46.256Z"}
info: Connected to the database. {"timestamp":"2022-02-21T13:23:46.287Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-21T13:24:21.206Z"}
info: Connected to the database. {"timestamp":"2022-02-21T13:24:21.229Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-21T13:24:42.011Z"}
info: Connected to the database. {"timestamp":"2022-02-21T13:24:42.034Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-21T13:28:33.952Z"}
info: Connected to the database. {"timestamp":"2022-02-21T13:28:33.978Z"}
error: 
    status - 500 
    message - ReferenceError: error is not defined
    at _callee3$ (/home/smita/RegisterUser/userRegistrationNlogin/src/services/user.service.js:21:22)
    at tryCatch (/home/smita/RegisterUser/userRegistrationNlogin/node_modules/regenerator-runtime/runtime.js:63:40)
    at Generator.invoke [as _invoke] (/home/smita/RegisterUser/userRegistrationNlogin/node_modules/regenerator-runtime/runtime.js:294:22)
    at Generator.next (/home/smita/RegisterUser/userRegistrationNlogin/node_modules/regenerator-runtime/runtime.js:119:21)
    at asyncGeneratorStep (/home/smita/RegisterUser/userRegistrationNlogin/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _next (/home/smita/RegisterUser/userRegistrationNlogin/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-02-21T13:28:35.781Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-21T13:28:58.294Z"}
info: Connected to the database. {"timestamp":"2022-02-21T13:28:58.315Z"}
error: 
    status - 500 
    message - ReferenceError: error is not defined
    at _callee3$ (/home/smita/RegisterUser/userRegistrationNlogin/src/services/user.service.js:21:22)
    at tryCatch (/home/smita/RegisterUser/userRegistrationNlogin/node_modules/regenerator-runtime/runtime.js:63:40)
    at Generator.invoke [as _invoke] (/home/smita/RegisterUser/userRegistrationNlogin/node_modules/regenerator-runtime/runtime.js:294:22)
    at Generator.next (/home/smita/RegisterUser/userRegistrationNlogin/node_modules/regenerator-runtime/runtime.js:119:21)
    at asyncGeneratorStep (/home/smita/RegisterUser/userRegistrationNlogin/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _next (/home/smita/RegisterUser/userRegistrationNlogin/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-02-21T13:29:02.406Z"}
error: 
    status - 500 
    message - ReferenceError: error is not defined
    at _callee3$ (/home/smita/RegisterUser/userRegistrationNlogin/src/services/user.service.js:21:22)
    at tryCatch (/home/smita/RegisterUser/userRegistrationNlogin/node_modules/regenerator-runtime/runtime.js:63:40)
    at Generator.invoke [as _invoke] (/home/smita/RegisterUser/userRegistrationNlogin/node_modules/regenerator-runtime/runtime.js:294:22)
    at Generator.next (/home/smita/RegisterUser/userRegistrationNlogin/node_modules/regenerator-runtime/runtime.js:119:21)
    at asyncGeneratorStep (/home/smita/RegisterUser/userRegistrationNlogin/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _next (/home/smita/RegisterUser/userRegistrationNlogin/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-02-21T13:29:04.911Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-21T13:29:19.824Z"}
info: Connected to the database. {"timestamp":"2022-02-21T13:29:19.844Z"}
error: 
    status - 500 
    message - ReferenceError: error is not defined
    at _callee3$ (/home/smita/RegisterUser/userRegistrationNlogin/src/services/user.service.js:21:22)
    at tryCatch (/home/smita/RegisterUser/userRegistrationNlogin/node_modules/regenerator-runtime/runtime.js:63:40)
    at Generator.invoke [as _invoke] (/home/smita/RegisterUser/userRegistrationNlogin/node_modules/regenerator-runtime/runtime.js:294:22)
    at Generator.next (/home/smita/RegisterUser/userRegistrationNlogin/node_modules/regenerator-runtime/runtime.js:119:21)
    at asyncGeneratorStep (/home/smita/RegisterUser/userRegistrationNlogin/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _next (/home/smita/RegisterUser/userRegistrationNlogin/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-02-21T13:29:22.894Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-21T13:29:39.684Z"}
info: Connected to the database. {"timestamp":"2022-02-21T13:29:39.705Z"}
error: 
    status - 500 
    message - ReferenceError: err is not defined
    at _callee3$ (/home/smita/RegisterUser/userRegistrationNlogin/src/services/user.service.js:21:22)
    at tryCatch (/home/smita/RegisterUser/userRegistrationNlogin/node_modules/regenerator-runtime/runtime.js:63:40)
    at Generator.invoke [as _invoke] (/home/smita/RegisterUser/userRegistrationNlogin/node_modules/regenerator-runtime/runtime.js:294:22)
    at Generator.next (/home/smita/RegisterUser/userRegistrationNlogin/node_modules/regenerator-runtime/runtime.js:119:21)
    at asyncGeneratorStep (/home/smita/RegisterUser/userRegistrationNlogin/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _next (/home/smita/RegisterUser/userRegistrationNlogin/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-02-21T13:29:41.741Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-21T13:30:12.917Z"}
info: Connected to the database. {"timestamp":"2022-02-21T13:30:12.938Z"}
error: 
    status - 500 
    message - ReferenceError: err is not defined
    at _callee3$ (/home/smita/RegisterUser/userRegistrationNlogin/src/services/user.service.js:21:22)
    at tryCatch (/home/smita/RegisterUser/userRegistrationNlogin/node_modules/regenerator-runtime/runtime.js:63:40)
    at Generator.invoke [as _invoke] (/home/smita/RegisterUser/userRegistrationNlogin/node_modules/regenerator-runtime/runtime.js:294:22)
    at Generator.next (/home/smita/RegisterUser/userRegistrationNlogin/node_modules/regenerator-runtime/runtime.js:119:21)
    at asyncGeneratorStep (/home/smita/RegisterUser/userRegistrationNlogin/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _next (/home/smita/RegisterUser/userRegistrationNlogin/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-02-21T13:30:15.399Z"}
error: 
    status - 500 
    message - ReferenceError: err is not defined
    at _callee3$ (/home/smita/RegisterUser/userRegistrationNlogin/src/services/user.service.js:21:22)
    at tryCatch (/home/smita/RegisterUser/userRegistrationNlogin/node_modules/regenerator-runtime/runtime.js:63:40)
    at Generator.invoke [as _invoke] (/home/smita/RegisterUser/userRegistrationNlogin/node_modules/regenerator-runtime/runtime.js:294:22)
    at Generator.next (/home/smita/RegisterUser/userRegistrationNlogin/node_modules/regenerator-runtime/runtime.js:119:21)
    at asyncGeneratorStep (/home/smita/RegisterUser/userRegistrationNlogin/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _next (/home/smita/RegisterUser/userRegistrationNlogin/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-02-21T13:30:19.531Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-21T13:31:24.267Z"}
info: Connected to the database. {"timestamp":"2022-02-21T13:31:24.288Z"}
error: 
    status - 500 
    message - ReferenceError: err is not defined
    at _callee3$ (/home/smita/RegisterUser/userRegistrationNlogin/src/services/user.service.js:21:22)
    at tryCatch (/home/smita/RegisterUser/userRegistrationNlogin/node_modules/regenerator-runtime/runtime.js:63:40)
    at Generator.invoke [as _invoke] (/home/smita/RegisterUser/userRegistrationNlogin/node_modules/regenerator-runtime/runtime.js:294:22)
    at Generator.next (/home/smita/RegisterUser/userRegistrationNlogin/node_modules/regenerator-runtime/runtime.js:119:21)
    at asyncGeneratorStep (/home/smita/RegisterUser/userRegistrationNlogin/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _next (/home/smita/RegisterUser/userRegistrationNlogin/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-02-21T13:31:26.311Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-21T13:31:49.124Z"}
info: Connected to the database. {"timestamp":"2022-02-21T13:31:49.147Z"}
error: 
    status - 500 
    message - Error: Invalid pasword
    at _callee3$ (/home/smita/RegisterUser/userRegistrationNlogin/src/services/user.service.js:32:13)
    at tryCatch (/home/smita/RegisterUser/userRegistrationNlogin/node_modules/regenerator-runtime/runtime.js:63:40)
    at Generator.invoke [as _invoke] (/home/smita/RegisterUser/userRegistrationNlogin/node_modules/regenerator-runtime/runtime.js:294:22)
    at Generator.next (/home/smita/RegisterUser/userRegistrationNlogin/node_modules/regenerator-runtime/runtime.js:119:21)
    at asyncGeneratorStep (/home/smita/RegisterUser/userRegistrationNlogin/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _next (/home/smita/RegisterUser/userRegistrationNlogin/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-02-21T13:31:53.006Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-21T13:32:11.990Z"}
info: Connected to the database. {"timestamp":"2022-02-21T13:32:12.011Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-21T13:34:09.796Z"}
info: Connected to the database. {"timestamp":"2022-02-21T13:34:09.820Z"}
error: 
    status - 500 
    message - Error: password does match
    at _callee3$ (/home/smita/RegisterUser/userRegistrationNlogin/src/services/user.service.js:32:13)
    at tryCatch (/home/smita/RegisterUser/userRegistrationNlogin/node_modules/regenerator-runtime/runtime.js:63:40)
    at Generator.invoke [as _invoke] (/home/smita/RegisterUser/userRegistrationNlogin/node_modules/regenerator-runtime/runtime.js:294:22)
    at Generator.next (/home/smita/RegisterUser/userRegistrationNlogin/node_modules/regenerator-runtime/runtime.js:119:21)
    at asyncGeneratorStep (/home/smita/RegisterUser/userRegistrationNlogin/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _next (/home/smita/RegisterUser/userRegistrationNlogin/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-02-21T13:34:13.778Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-21T13:34:22.340Z"}
info: Connected to the database. {"timestamp":"2022-02-21T13:34:22.362Z"}
error: 
    status - 500 
    message - Error: password does match
    at _callee3$ (/home/smita/RegisterUser/userRegistrationNlogin/src/services/user.service.js:32:13)
    at tryCatch (/home/smita/RegisterUser/userRegistrationNlogin/node_modules/regenerator-runtime/runtime.js:63:40)
    at Generator.invoke [as _invoke] (/home/smita/RegisterUser/userRegistrationNlogin/node_modules/regenerator-runtime/runtime.js:294:22)
    at Generator.next (/home/smita/RegisterUser/userRegistrationNlogin/node_modules/regenerator-runtime/runtime.js:119:21)
    at asyncGeneratorStep (/home/smita/RegisterUser/userRegistrationNlogin/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _next (/home/smita/RegisterUser/userRegistrationNlogin/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-02-21T13:34:26.329Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-21T13:35:02.005Z"}
info: Connected to the database. {"timestamp":"2022-02-21T13:35:02.032Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-21T13:35:32.528Z"}
info: Connected to the database. {"timestamp":"2022-02-21T13:35:32.548Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-21T13:37:08.509Z"}
info: Connected to the database. {"timestamp":"2022-02-21T13:37:08.530Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-02-21T13:37:58.436Z"}
info: Connected to the database. {"timestamp":"2022-02-21T13:37:58.457Z"}
